ft_runall: Use a fixed number of iterations
The script is intended as a quick validation check.  Only
exchange a handful of messages.  (Longer term, the script
should be extended with better capabilities.)

Signed-off-by: Sean Hefty <sean.hefty@intel.com>

diff --git a/scripts/ft_runall b/scripts/ft_runall
--- a/scripts/ft_runall
+++ b/scripts/ft_runall
@@ -1,3 +1,8 @@
+if [ $# -eq 0 ] ; then
+   echo "Server address required"
+   exit 1
+fi
+
 echo Running fi_info
 fi_info
 echo ...done
@@ -5,121 +10,121 @@ sleep 3
 echo Running fi_msg
 fi_msg &
 sleep 3
-fi_msg 127.0.0.1
+fi_msg $1
 echo ...done 
 sleep 3
 echo Running fi_msg_pingpong
-fi_msg_pingpong &
+fi_msg_pingpong -I 5 &
 sleep 3
-fi_msg_pingpong 127.0.0.1
+fi_msg_pingpong -I 5 $1
 echo ...done 
 sleep 3
 echo Running fi_msg_rma
-fi_msg_rma &
+fi_msg_rma -I 5 &
 sleep 3
-fi_msg_rma 127.0.0.1
+fi_msg_rma -I 5 $1
 echo ...done 
 sleep 3
 echo Running fi_rdm
 fi_rdm &
 sleep 3
-fi_rdm 127.0.0.1
+fi_rdm $1
 echo ...done 
 sleep 3
 echo Running fi_rdm_rma_simple
 fi_rdm_rma_simple &
 sleep 3
-fi_rdm_rma_simple 127.0.0.1
+fi_rdm_rma_simple $1
 echo ...done 
 sleep 3
 echo Running fi_dgram
 fi_dgram &
 sleep 3
-fi_dgram 127.0.0.1
+fi_dgram $1
 echo ...done 
 sleep 3
 echo Running fi_dgram_waitset
 fi_dgram_waitset &
 sleep 3
-fi_dgram_waitset 127.0.0.1
+fi_dgram_waitset $1
 echo ...done 
 sleep 3
 echo Running fi_rdm_pingpong
-fi_rdm_pingpong &
+fi_rdm_pingpong -I 5 &
 sleep 3
-fi_rdm_pingpong 127.0.0.1
+fi_rdm_pingpong -I 5 $1
 echo ...done 
 sleep 3
 echo Running fi_rdm_tagged_pingpong
-fi_rdm_tagged_pingpong &
+fi_rdm_tagged_pingpong -I 5 &
 sleep 3
-fi_rdm_tagged_pingpong 127.0.0.1
+fi_rdm_tagged_pingpong -I 5 $1
 echo ...done 
 sleep 3
 echo Running fi_rdm_tagged_search
 fi_rdm_tagged_search &
 sleep 3
-fi_rdm_tagged_search 127.0.0.1
+fi_rdm_tagged_search $1
 echo ...done 
 sleep 3
 echo Running fi_rdm_cntr_pingpong
-fi_rdm_cntr_pingpong &
+fi_rdm_cntr_pingpong -I 5 &
 sleep 3
-fi_rdm_cntr_pingpong 127.0.0.1
+fi_rdm_cntr_pingpong -I 5 $1
 echo ...done 
 sleep 3
 echo Running fi_rdm_rma
-fi_rdm_rma &
+fi_rdm_rma -I 5 &
 sleep 3
-fi_rdm_rma 127.0.0.1
+fi_rdm_rma -I 5 $1
 echo ...done 
 sleep 3
 echo Running fi_rdm_atomic
-fi_rdm_atomic &
+fi_rdm_atomic -I 5 &
 sleep 3
-fi_rdm_atomic 127.0.0.1
+fi_rdm_atomic -I 5 $1
 echo ...done 
 sleep 3
 echo Running fi_ud_pingpong
-fi_ud_pingpong &
+fi_ud_pingpong -I 5 &
 sleep 3
-fi_ud_pingpong 127.0.0.1
+fi_ud_pingpong -I 5 $1
 echo ...done 
 sleep 3
 echo Running fi_cq_data
 fi_cq_data &
 sleep 3
-fi_cq_data 127.0.0.1
+fi_cq_data $1
 echo ...done 
 sleep 3
 echo Running fi_poll
 fi_poll &
 sleep 3
-fi_poll 127.0.0.1
+fi_poll $1
 echo ...done 
 sleep 3
 echo Running fi_rdm_inject_pingpong
-fi_rdm_inject_pingpong &
+fi_rdm_inject_pingpong -I 5 &
 sleep 3
-fi_rdm_inject_pingpong 127.0.0.1
+fi_rdm_inject_pingpong -I 5 $1
 echo ...done 
 sleep 3
 echo Running fi_rdm_multi_recv
 fi_rdm_multi_recv &
 sleep 3
-fi_rdm_multi_recv 127.0.0.1
+fi_rdm_multi_recv $1
 echo ...done 
 sleep 3
 echo Running fi_scalable_ep
 fi_scalable_ep &
 sleep 3
-fi_scalable_ep 127.0.0.1
+fi_scalable_ep $1
 echo ...done 
 sleep 3
 echo Running fi_rdm_shared_ctx
 fi_rdm_shared_ctx &
 sleep 3
-fi_rdm_shared_ctx 127.0.0.1
+fi_rdm_shared_ctx $1
 echo ...done 
 sleep 3
 echo Running fi_eq_test
@@ -135,19 +140,19 @@ fi_size_left_test
 echo ...done 
 sleep 3
 echo Running fi_rc_pingpong
-fi_rc_pingpong &
+fi_rc_pingpong -n 5 &
 sleep 3
-fi_rc_pingpong 127.0.0.1
+fi_rc_pingpong -n 5 $1
 echo ...done 
 sleep 3
 echo Running fi_cmatose
-fi_cmatose &
+fi_cmatose -C 5 &
 sleep 3
-fi_cmatose -s 127.0.0.1
+fi_cmatose -s $1 -C 5 
 echo ...done 
 sleep 3
 echo fabtest
 fabtest -x &
 sleep 3
-fabtest 127.0.0.1
+fabtest $1
 echo ...done
